---

- name: "Delete customer services"
  with_dict: "{{ ansible_local.customers.ids }}"
  loop_control:
    loop_var: outer_item
  include_role: 
    name: del-customer-services
  vars:
    segment_id: "{{ outer_item.key }}"
    bigip_cluster_members_leaving: True
#  when: bigip_cluster_member[id] == False
  tags:
    - del

